- id: doi:10.1016/j.iot.2021.100462
  type: paper
  description: Intrusion detection based on Machine Learning techniques in computer networks
  date: 2021-12-1
  buttons:
    - type: source
      text: Manuscript Source
      link: https://www.sciencedirect.com/science/article/abs/pii/S2542660521001037


- id: doi:10.1016/j.iot.2023.100699
  type: paper
  
- id: doi:10.1109/ACCESS.2022.3205337
  type: paper
  buttons:
  - type: source
    text: Manuscript Source
    link: https://ieeexplore.ieee.org/mediastore/IEEE/content/media/6287639/9668973/9882118/maniv2ab-3205337-small.gif

- id: doi:10.1145/3627106.3627193
  type: paper
- id: doi:10.1093/bioinformatics/btz559
  type: paper

- id: doi:10.1109/IWCMC58020.2023.10182609
  type: paper

- id: doi:10.13023/etd.2023.292
  type: paper

- id: doi:10.1101/454686
  type: paper
  image: https://www.biorxiv.org/content/biorxiv/early/2018/10/26/454686/F1.medium.gif

- id: doi:10.32473/flairs.38.1.138858
  image: https://journals.flvc.org/public/journals/107/cover_issue_6467_en_US.png








